### ISSUE TITLE
jws_validation role fails when using non-default tomcat version

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#125]
##### SUMMARY

If you update the tomcat version that you're using, but don't set `tomcat_home`, then the jws_validation role fails.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/csutherl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.12 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
```

##### COLLECTION VERSION

The latest tagged version, 1.1.1.

##### STEPS TO REPRODUCE

Update the sample playbook and change `tomcat_version` to `9.0.60` rather than `9.0.50` and execute the playbook. Everything runs smoothly until it gets to validation, which fails.

##### EXPECTED RESULTS

Successful execution of the molecule scenario.

##### ACTUAL RESULTS

```
molecule test
....
TASK [jws_validation : Read the content of catalina.out] *********************************************************************************************************************************************************************************************************************************************************************
fatal: [instance]: FAILED! => {"changed": false, "msg": "file not found: /opt/apache-tomcat-9.0.50/logs/catalina.out"}
```

It appears that we didn't replicate the logic from 5a5311ac in the jws role to the jws_validation role, so now the dynamic setting of tomcat_home only happens within on role leaving the other to have a bad default value.

**Comment by rpelisse** [comment]
This has been refactored away by the recent re-engineering, so I'm closing it.
