### ISSUE TITLE
Cleaning up zips after installation.

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws-ansible-playbook#143]
##### SUMMARY

When zips are downloaded from RHN to control node and/or control node to the target hosts, the zips are left over in the target hosts after installation. Should they be kept there or be cleaned up?

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
We need to keep them there otherwise the collection will download them again. It all has to do with Ansible idempotency. If there is a customer request, at some point, to remove them, we can investigate this, but from Ansible point of view, it's a best practice to keep it there (at least IMHO).

**Comment by csutherl** [comment]
Is that an acceptable answer @defeatedbylife ? Can we close this?
