### ISSUE TITLE
Installallation on APR, OpenSSL when tomcat_native set to False

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws-ansible-playbook#144]
##### SUMMARY

Does APR and OpenSSL need to be installed when tomcat natives are not?

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
APR, I'm not sure, maybe @csutherl can confirm or infirm. OpenSSL I suspect is use implicitly by the HTTPS connector, whether or not tomcat native is installed. @guidograzioli WDYT?

**Comment by csutherl** [comment]
No, if you're not using tomcat-native then you don't need APR or OpenSSL since encryption/decryption is handled by the JDK. OpenSSL can't be used by Tomcat (Java) without JNI which is provided by the tomcat-native library.

**Comment by rpelisse** [comment]
@csutherl This is fixed by [PR159](https://github.com/ansible-middleware/jws-ansible-playbook/pull/159), right? I think we can close this issue or is there more work to be done?

**Comment by csutherl** [comment]
@rpelisse yeah, I think this is all done.
