### ISSUE TITLE
AJP connector mentioned in HTTPS sanity checks.

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws-ansible-playbook#168]
##### SUMMARY

The name and fail message in https sanity checks mentions AJP connector, not the HTTPS connector.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```
1.1.1
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by rpelisse** [comment]
Copy'n'paste is death.

Fixed by [commit 78f8104218c50664c3bc89d7416ddc7008ade2a2](https://github.com/ansible-middleware/jws-ansible-playbook/commit/78f8104218c50664c3bc89d7416ddc7008ade2a2)
