### ISSUE TITLE
Remove, as much as possible, reference to Tomcat

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/jws-ansible-playbook#42]
##### SUMMARY

The handler to restart the service is named "Restart tomcat service" should be renamed to "Restart JBoss Web Server service" (or an even more generic name if possible). We should also look for other occurrences of this issue.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by guidograzioli** [comment]
Closed by PR #43
