### ISSUE TITLE
Running the playbook with a running Tomcat server fails

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#71]
##### SUMMARY
If you run the playbook on a target which has Tomcat already running the check for the tomcat user causes a failure with the following output:

`
TASK [middleware_automation.jws.jws : Create user for tomcat: tomcat] ********************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "usermod: user tomcat is currently used by process 8915\n", "name": "tomcat", "rc": 8}
`

The problem is clear in the message, but it seems that we don't have a way to handle this situation. I think that we could add a feature to behave differently when Tomcat is already running on the host and fail a bit more gracefully, or replace the currently running instance with the new one (the latter option seems the more Ansible-like thing to do IMO).

##### ISSUE TYPE
 - Feature Idea

**Comment by csutherl** [comment]
Reproduction steps:

* Create a new Fedora 35 VM
* Install the collection tarball so that the `redhat_csp_download` dep is satisfied
* Execute the playbook against localhost (with default tomcat version 9.0.50) and wait for success
* Update the playbook to use tomcat version 9.0.62
* Execute the playbook against localhost again

The user check fails when you change the version, but succeeds if you don't.

**Comment by rpelisse** [comment]
@csutherl I think this need to arbitrated on your side. We can go with a "control file", something like "{{ tomcat_home }}/ansible_installed", and if it's missing we check that the target is NOT already running a server. However, it make sense only if it is a valid use case (people using the collection will need that).

**Comment by csutherl** [comment]
My first thought after reading @guidograzioli's reply was that we could add a marker file, but on second thought the solution of checking that a node is already running and alerting the user is probably good enough. We could do that in combination with adding a `tomcat_force_install` parameter that we could also use as a `force_update` too? If a user opts to force an install/update then I'd hope that they understand the risk of updating a server that was not installed with this collection.
