### ISSUE TITLE
local_zipfiles doesn't work with JWS zips

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#87]
##### SUMMARY
Reading the commented out use case 4 in the sample playbook reads as if you can use `local_zipfiles` method to install your JWS zips. I tried it and it fails :(

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /root/.ansible/collections/ansible_collections/middleware_automation/jws/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
```

##### COLLECTION VERSION

Using a local build of the collection based on commit 127406bbed2e525aedf91f1c79c7f86915106cc9.

##### STEPS TO REPRODUCE

Download JWS zips and drop them into `/opt`.
Update playbook to use local_zipfiles and specify `jws_version` (see sample below).
Execute playbook.

```yaml
    # Use Case 4 - install JWS from local zipfiles
    tomcat_install_method: local_zipfiles
    tomcat_home: "{{ tomcat_install_dir }}/jws-5.6/tomcat"
    jws_version: 5.6.0
```

##### EXPECTED RESULTS

I expect that the JWS zips will be installed as they are locally available.

##### ACTUAL RESULTS

The execution fails. It appears that even though I set `jws_version` it still expects me to define `tomcat_zipfile` (it uses the default `tomcat_zipfile`).

```
TASK [middleware_automation.jws.jws : Install Tomcat and required binaries from local zipfiles (install method: local_zipfiles] **********************************************************************************************************************************************************************************************
failed: [localhost] (item={'src': 'apache-tomcat-9.0.60.zip', 'creates': '/opt/jws-5.6/tomcat/bin'}) => {"ansible_loop_var": "item", "changed": false, "item": {"creates": "/opt/jws-5.6/tomcat/bin", "src": "apache-tomcat-9.0.60.zip"}, "msg": "Source '/opt/apache-tomcat-9.0.60.zip' does not exist"}
```

**Comment by guidograzioli** [comment]
It seems a documentation issue; for JWS install from local zips, it should be `tomcat_install_method: rhn_zipfiles` like [here](https://github.com/ansible-middleware/jws-ansible-playbook/blob/main/playbook.yml#L23) (the same as use case 3, with the only difference that files where already downloaded from the portal and placed in the playbook directory)
