### ISSUE TITLE
Download from URL

### ISSUE THREAD

**Issue by sabre1041** [ansible-middleware/jws-ansible-playbook#9]
There should be an ability to download the installation media from a remote location (such as an artifact server [Nexus/Artifactory])

**Comment by sabre1041** [comment]
while the unarchive module can provide a URL, there is no support for protected (authenticated) content

**Comment by rpelisse** [comment]
We can indeed replace unarchive: by get_url: + unarchive:, that should not be too difficult.

**Comment by rpelisse** [comment]
@rpelisse Just look at this issue again, I'm not sure what change you wish to see. Do you want to add a get_url: task so that the user can provided an URL rather than a path to zipfile directly? Is that the requirement here? Or did I misunderstood something?
