### ISSUE TITLE
Task name uses item variable which doesn't get interpolated

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#95]
The name of this task uses `{{ item.template }}` which doesn't get interpolated at runtime and should be removed. I didn't have time to submit a PR today but filing so I don't forget.

https://github.com/ansible-middleware/jws-ansible-playbook/blob/c2f074d17b640246256bf37d67cce64606cabafa/roles/jws/tasks/main.yml#L108

**Comment by rpelisse** [comment]
Fixed by [PR96](https://github.com/ansible-middleware/jws-ansible-playbook/pull/96)
