### ISSUE TITLE
tomcat-vault documentation is missing

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#98]
##### SUMMARY
There is currently no documentation on how to utilize the tomcat-vault feature. I've walked through setting it up with the tomcat-vault instructions and we're missing the instruction to tell users to create the initial keystore, if you don't do that then the copy step will cause failure.

##### ISSUE TYPE
 - Feature Idea

**Comment by csutherl** [comment]
I was going to suggest creating a default keystore and use that to init the vault, however in practical usage I don't think it makes sense for our collection to create a new vault. If we did create a new vault for users, then they wouldn't be able to provide configuration files that are using the vault until after they created new strings with the new vault.

**Comment by csutherl** [comment]
Forgot a step, you need to update Tomcat's `conf/catalina.properties` to load the vault classes too or it won't be in use :)

**Comment by csutherl** [comment]
No, I'll work on something to suggest to add to the documentation this week.

**Comment by csutherl** [comment]
I think this issue is now blocked by #149 in case there are changes introduced.

**Comment by csutherl** [comment]
@defeatedbylife thoughts on the PR?

**Comment by rpelisse** [comment]
As clarified in #149, there is no relation between this issue and #127. As for the tomcat_vault documentation itself, I'm happy with the current content, so I would suggest we close this issue (as done).

**Comment by csutherl** [comment]
Would love to get feedback from @defeatedbylife before closing.
